name = "app"
[store]
text = "string"
num = "number"
props = []
state = []
[actions]
    [change]
        text = "string"
    [inc]
    [dec]
        num = "number"

[reducer]
    change = "state.text = action.text"
    inc = "num = state.num + 1"
    dec = "num = state.num - action.num"


[[node]]
    type = "std.HTML.input"
    id = "aaa"
    parent = "root"
    child = [  ]
    className = [ "aaa", "bbb" ]
    [node.attribute]
        test = "text"
[[node]]
    type = "std.HTML.input"
    id = "bbb"
    parent = "aaa"
    child = [  ]
    className = [ "aaa", "bbb" ]
    [node.attribute]
        test = "number"

