name = "App"
props = []
state = []
[store]
text = "string"
num = "number"
[actions]
    [change]
        text = "string"
    [inc]
    [dec]
        num = "number"

[reducer]
    change = "state.text = action.text"
    inc = "num = state.num + 1"
    dec = "num = state.num - action.num"


[[node]]
    type = "div"
    id = "aaa"
    parent = "root"
    children = [ "bbb" ]
    className = [ "aaa", "bbb" ]
    [node.attribute]
        className = "\"text\""
[[node]]
    type = "p"
    id = "bbb"
    parent = "aaa"
    children = [  ]
    className = [ "aaa", "bbb" ]
    [node.attribute]
        className = "\"number\""

