name = "App"
props = []
state = []
[store]
text = "string"
num = "number"
[actions]
    [actions.change]
        text = "string"
    [actions.inc]
    [actions.dec]
        num = "number"

[reducer]
    change = "state.text = action.text"
    inc = "num = state.num + 1"
    dec = "num = state.num - action.num"


[[node]]
    tag = "div"
    id = "aaa"
    parent = "root"
    children = [ "bbb", "c" ]
    className = [ "aaa", "bbb" ]
    [node.attribute]
        className = "\"text\""
[[node]]
    tag = "p"
    id = "bbb"
    parent = "aaa"
    children = [ "d" ]
    className = [ "aaa", "bbb" ]
    [node.attribute]
        className = "\"number\""
[[node]]
    tag = "input"
    id = "c"
    parent = "aaa"
    children = [  ]
    className = [ "aaa", "bbb" ]
    [node.attribute]
        type = "\"number\""
[[node]]
    tag = "text"
    id = "d"
    parent = "c"
    children = [  ]
    className = [ "aaa", "bbb" ]
    [node.attribute]
        text = "テスト"

